// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/sungpaik/Documents/FullStackAcademy/Senior-Phase/realTestBoilerPlate/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/sungpaik/Documents/FullStackAcademy/Senior-Phase/realTestBoilerPlate/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('ViroSample', appParameters);
});
var entryPoint = require('/Users/sungpaik/Documents/FullStackAcademy/Senior-Phase/realTestBoilerPlate/index.js');